tools:
  external_code_coverage:
    timeout: 600

checks:
  php:
      code_rating: true
      duplication: true

filter:
  excluded_paths:
    - vendor/*
    - tests/*
    - bootstrap.php

build_failure_conditions:
  - 'elements.rating(<= C).new.exists'                        # No new classes/methods with a rating of C or worse allowed
  - 'issues.severity(>= MAJOR).new.exists'                    # New issues of major or higher severity
  - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection